// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwxGwLf1FnzboxE-ABQ5vjKG4OYa_798w',
    appId: '1:926599048624:web:ddb822e26bf0896455ba75',
    messagingSenderId: '926599048624',
    projectId: 'couple-alarm-569c8',
    authDomain: 'couple-alarm-569c8.firebaseapp.com',
    storageBucket: 'couple-alarm-569c8.firebasestorage.app',
    measurementId: 'G-VMR20W812P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvhxZSE7duCxogoEmWH-ZPQ0ytYXEW3oU',
    appId: '1:926599048624:android:32438ea3472762c755ba75',
    messagingSenderId: '926599048624',
    projectId: 'couple-alarm-569c8',
    storageBucket: 'couple-alarm-569c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9P54IBjWkpxdr7FstrF6ErQKRi0QbxGk',
    appId: '1:926599048624:ios:cfb9f2501e2e4b0355ba75',
    messagingSenderId: '926599048624',
    projectId: 'couple-alarm-569c8',
    storageBucket: 'couple-alarm-569c8.firebasestorage.app',
    iosClientId: '926599048624-ktk5bc4c4olrtmq1ior34u3v8k6stm1q.apps.googleusercontent.com',
    iosBundleId: 'com.yorxbit.couplealarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9P54IBjWkpxdr7FstrF6ErQKRi0QbxGk',
    appId: '1:926599048624:ios:cf43cb9b8e5d4c0d55ba75',
    messagingSenderId: '926599048624',
    projectId: 'couple-alarm-569c8',
    storageBucket: 'couple-alarm-569c8.firebasestorage.app',
    iosClientId: '926599048624-9d3l9498fmlsss4tkc08j0sbk1jimmqq.apps.googleusercontent.com',
    iosBundleId: 'com.example.coupleNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwxGwLf1FnzboxE-ABQ5vjKG4OYa_798w',
    appId: '1:926599048624:web:81e6f912f6f647fc55ba75',
    messagingSenderId: '926599048624',
    projectId: 'couple-alarm-569c8',
    authDomain: 'couple-alarm-569c8.firebaseapp.com',
    storageBucket: 'couple-alarm-569c8.firebasestorage.app',
    measurementId: 'G-N1GRX819E3',
  );

}